project:
  type: website

website:
  title: "ISSS608-VAA-Project"
  navbar:
    left:
      - href: index.html
        text: Home
      - text: Project
        menu:
          - href: project_proposal.html
            text: Project Proposal
          - href: Take-Home_Ex03.html
            text: Prototype
          - href: data-prep.html
            text: Data Preparation
          - href: CDA_Webpage.html
            text: Confirmiatory Data Analysis
      - href: about.html
        text: About Us
        
    right: 
      - href: https://isss608-ay2024-25apr-jylau.shinyapps.io/DeepDiving/
        text: 📱 ShinyApp

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

