project:
  type: website

website:
  title: "ISSS608-VAA-Project"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: project_proposal.qmd
        text: Project Proposal
      - href: Take-Home_Ex03.qmd
        text: Take Home Exercise 03
      - about.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

